### ISSUE TITLE
Typo in distribute, adding a tier section.

### ISSUE THREAD

**Issue by philderbeast** [aviaviavi/scarf#15]
At https://docs.scarf.sh/distribute-with-scarf/#adding-a-private-usage-tier-to-your-package there's a typo:

```diff
-- patiend
++ patient
```

**Comment by aviaviavi** [comment]
Thanks for opening @philderbeast! 

Our doc repo has moved to https://github.com/scarf-sh/docs, where this typo has now been fixed.
