### ISSUE TITLE
How do you know which company someone works for?

### ISSUE THREAD

**Issue by joncodo** [aviaviavi/scarf#28]
Is this based on their email when they register?

How is the code implemented?

What percentage of users can you say you can determine company for? 10%? 15%? 100%?

Thanks! Great product

**Comment by aviaviavi** [comment]
Hi @joncodo, thanks for reaching out! 

Companies are identified with reverse IP lookup from various providers. You can see https://docs.scarf.sh/gateway/#faq with more information on the data we store and expose.

> How is the code implemented?

Our backend/analytics pipeline is not open-source (this repo is actually not for Scarf Gateway, which you are trying out in the linked issue in merico-dev/lake, but rather, an experimental system package manager that's more of a long-term project for us), but I'm happy to discuss the implementation if there are any specific questions you have. It's documented at a high level in our docs, but overall, we look up whatever metadata we can from the IP address from external data providers, and then we discard the raw IP from our system (for GDPR compliance)

> What percentage of users can you say you can determine company for? 10%? 15%? 100%?

This is difficult to accurately estimate, if we had the theoretical "source of truth" to use as a benchmark, then we'd be using that dataset instead :) IP metadata is certainly not an exact strategy, but still surfaces quite a bit in the aggregate. Public wifi, personal VPN's, etc will all hide the employer information of a user. But we surface quite a lot of commercial usage for other Scarf users. We're closer to 50% than 100%, but it's really to get specific at this time.

Let me now if you have any other questions!

**Comment by joncodo** [comment]
Thank you for your quick reply. I have set up our repo here: https://scarf.sh/gateway/joncodo/docker/mericodev%2Fconfig-ui

I don't see any companies as of yet. I expected to see meri.co in the list but it did not show up. 

Would I be more likely to see larger companies like goole or amazon?

**Comment by aviaviavi** [comment]
Right, so that means the IP address(es) you pulled the container from are not registered to Merico directly, or not registered as a business-categorized IP. As you pointed out, the data is definitely skewed towards larger companies for this reason, as younger companies are less likely to have these registered IP addresses/blocks. As we bring in more metadata providers, this will get smarter and smarter, but for now, it's really about the IP address metadata from our external data providers.
